#!/usr/bin/env python3
"""
georef_nodes.py — Convert plaza node local coordinates to UTM 17N so SUMO FCD geo-output
(--fcd-output.geo) emits real lon/lat without any runtime fit.

Coordinate convention (MUST match transform.js sign convention):
  east  = (x - sumoRefX)*sin(b) - (y - sumoRefY)*cos(b)
  north = (x - sumoRefX)*cos(b) + (y - sumoRefY)*sin(b)
  UTM_E = E0 + east
  UTM_N = N0 + north

Anchor: sumoRefX=530, sumoRefY=0 maps to anchorLon=-80.306, anchorLat=26.1124.
Bearing: 104 deg (CW from north).
Scale: 1.0 (true-to-scale; 1 SUMO m = 1 real m).

Writes the 6 nodes as UTM 17N coordinates into plaza.nod.xml.
The edges (plaza.edg.xml) and connections (plaza.con.xml) reference nodes by id only — no change.
"""
from math import radians, sin, cos
from pyproj import Transformer

HERE = __file__[: __file__.rfind("/")]

# --- I-595 anchor (same as SITES[0] in main.js) ---
ANCHOR_LON = -80.306
ANCHOR_LAT = 26.1124
BEARING_DEG = 104.0
SUMO_REF_X = 530.0
SUMO_REF_Y = 0.0

# WGS84 -> UTM 17N (EPSG:32617)
_fwd = Transformer.from_crs("EPSG:4326", "EPSG:32617", always_xy=True)
E0, N0 = _fwd.transform(ANCHOR_LON, ANCHOR_LAT)

_b = radians(BEARING_DEG)
_s, _c = sin(_b), cos(_b)


def local_to_utm(x, y):
    """Convert a plaza local coord (x along-corridor, y lateral) to UTM 17N easting/northing."""
    dx = x - SUMO_REF_X
    dy = y - SUMO_REF_Y
    east = dx * _s - dy * _c   # identical to transform.js sumoToWorld (scale=1)
    north = dx * _c + dy * _s
    return E0 + east, N0 + north


# --- Plaza node definitions (local coords) ---
NODES = [
    ("A", 0,   0, "priority"),   # approach start (west)
    ("B", 400, 0, "priority"),   # fan-out / widen begins
    ("C", 500, 0, "priority"),   # booth entry
    ("D", 530, 0, "priority"),   # booth exit / anchor
    ("E", 630, 0, "priority"),   # fan-in / merge ends
    ("F", 930, 0, "priority"),   # departure end (east)
]

XML_HEADER = """\
<?xml version="1.0" encoding="UTF-8"?>
<!-- I-595 toll-plaza — nodes in UTM 17N (EPSG:32617), generated by georef_nodes.py.
     Do NOT hand-edit; re-run: python3 sumo/georef_nodes.py
     Anchor: lon={lon}, lat={lat} (sumoRefX={rx}, sumoRefY={ry}), bearing={b} deg, scale=1.
     UTM anchor: E={E0:.3f}, N={N0:.3f} -->
<nodes>
""".format(lon=ANCHOR_LON, lat=ANCHOR_LAT, rx=SUMO_REF_X, ry=SUMO_REF_Y, b=BEARING_DEG, E0=E0, N0=N0)

XML_FOOTER = "</nodes>\n"


def main():
    out_path = HERE + "/plaza.nod.xml"
    lines = [XML_HEADER]
    for nid, lx, ly, ntype in NODES:
        e, n = local_to_utm(lx, ly)
        lines.append(
            f'  <node id="{nid}" x="{e:.3f}" y="{n:.3f}" type="{ntype}"/>'
            f'  <!-- local x={lx}, y={ly} -->\n'
        )
    lines.append(XML_FOOTER)
    with open(out_path, "w") as f:
        f.write("".join(lines))
    print(f"Wrote {out_path}")
    for nid, lx, ly, _ in NODES:
        e, n = local_to_utm(lx, ly)
        print(f"  {nid}: local({lx},{ly}) -> UTM E={e:.3f}, N={n:.3f}")


if __name__ == "__main__":
    main()
